### ISSUE TITLE
failed to create temporary file on Ubuntu Jammy

### ISSUE THREAD

**Issue by mv-2112** [Nightmayr-snaps/amazon-workspaces-snap#1]
Attempting to connect to a workspace using the workspaces client fails.
When launched from console following error message is seen.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to create temporary file
Aborted (core dumped)
```

**Comment by Nightmayr** [comment]
Hi thanks for the report, I can confirm I see the same on my end. It's a problem where workspaces was trying to write to a file under `/dev/shm` but wasn't allowed due to sandboxing. Pushed a change that fixes the problem https://github.com/Nightmayr-snaps/amazon-workspaces-snap/commit/18d35452ded1f45e32088944cc3135d3a943fcd9. Revision 6 should contain the fix, let me know if it fixes the crash for you.

**Comment by mv-2112** [comment]
Hi there, apologies only had time to test today, can confirm works as it should after patch! Thank you!
